In [2]:
# import pandas as pd
from pathlib import Path

# from posydon.popsyn10Gyr.binarypopulation import BinaryPopulation
# from posydon.binary_evol.binarystar import BinaryStar
# from posydon.binary_evol.singlestar import SingleStar
from posydon.popsyn.synthetic_population import Population
# from posydon.popsyn.synthetic_population import PopulationRunner
# import astropy.units as u

# import os
# import shutil
# from posydon.config import PATH_TO_POSYDON

# from POSYDONHRDiagramModule import HR_Diagram

# import matplotlib.pyplot as plt

# import random as rand

In [3]:
cols = ['time', 'step_names', 'state', 'event', 'S1_state', 'S2_state', 'S1_mass', 'S2_mass', 'orbital_period']
finCols = [
    'orbital_period_f',
    'eccentricity_f',
    'state_f',

    'S1_state_f',
    'S2_state_f',
    
    'S2_mass_f',
    'S2_log_R_f',
    'S2_log_L_f',


    'S1_mass_f',
    'S1_log_R_f',
    'S1_log_L_f'

 ]

initCols = [
    'orbital_period_i',
    'eccentricity_i',
    'state_i',

    'S2_state_i',
    'S2_mass_i',
    'S2_log_R_i',

    'S1_state_i',
    'S1_mass_i',
    'S1_log_R_i'
 ]

In [4]:
DataPath = Path().resolve().parent.parent.parent / 'Data'

In [5]:
pop = Population(str(DataPath / '1e+00_Zsun_population.h5'))

Missing ini parameter: posydon_version

In [6]:
len(pop)

1000000

In [7]:
# bh_solarCond_oneline = "((S1_state_f == 'H-rich_Core_H_burning') & (S2_state_f == 'BH')) | " \
#                "((S2_state_f == 'H-rich_Core_H_burning') & (S1_state_f == 'BH'))"
    
bh_solarCond_history = "((S2_state == 'H-rich_Core_H_burning') & (S1_state == 'BH')) " \
                        "& (state == 'detached')"

In [8]:
# solBHdf_oneline = pop.oneline.select(where = bh_solarCond_oneline)

solBHdf_history = pop.history.select(where = bh_solarCond_history)

In [9]:
len(solBHdf_history)

41247

In [14]:
solBHdf_history

,state,event,time,separation,orbital_period,eccentricity,rl_relative_overflow_1,rl_relative_overflow_2,lg_mtransfer_rate,step_names,...,S2_conv_env_turnover_time_l_b,S2_conv_env_turnover_time_l_t,S2_envelope_binding_energy,S2_mass_conv_reg_fortides,S2_thickness_conv_reg_fortides,S2_radius_conv_reg_fortides,S2_lambda_CE_1cent,S2_lambda_CE_10cent,S2_lambda_CE_30cent,S2_lambda_CE_pure_He_star_10cent
binary_index,,,,,,,,,,,,,,,,,,,,,
34,detached,NaN,1.354658e+10,1131.739444,773.934254,0.706087,NaN,NaN,NaN,step_SN,...,0.000000e+00,-2.162275e+97,-1.468406e+50,4.762350e-06,0.347870,9.396873,1.118066,1.118066,1.118066,1.118093
40,detached,NaN,9.365578e+08,74.435662,13.464326,0.221966,NaN,NaN,NaN,step_SN,...,0.000000e+00,-5.929734e+98,-1.739592e+50,1.689453e+00,0.363708,2.030009,0.899983,0.719876,0.720830,1.184937
66,detached,NaN,7.320985e+08,198.318680,42.991418,0.046120,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-2.504154e+50,1.177150e-01,3.231943,19.644430,0.592405,0.232861,0.265062,0.592405
83,detached,NaN,4.982609e+08,50.407465,10.559919,0.639463,NaN,NaN,NaN,step_SN,...,-1.834669e+87,-1.000000e+99,-7.499487e+49,3.481643e-07,0.031008,4.687843,1.295121,1.295121,1.295121,1.295121
86,detached,NaN,1.001154e+10,176.105411,38.437130,0.318287,NaN,NaN,NaN,step_SN,...,0.000000e+00,-6.928767e+98,-2.679997e+50,2.561434e-05,0.951441,13.888433,1.342558,1.343758,1.036638,1.342558
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999858,detached,NaN,8.317989e+09,63.091987,10.937788,0.190515,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-1.291544e+50,3.205125e-06,0.213334,6.881290,1.173028,1.173028,1.173028,1.173162
999861,detached,NaN,1.068474e+10,883.381417,573.468964,0.432775,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-7.867066e+49,5.785900e-07,0.038229,4.391969,1.311851,1.311851,1.311851,1.314639
999931,detached,NaN,9.064239e+09,7530.879233,18964.253312,0.969098,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-8.444020e+49,1.939937e-01,0.108014,4.283201,1.090792,1.090792,1.090792,1.091467
999940,detached,NaN,9.362281e+09,9.474144,0.941797,0.688918,NaN,NaN,NaN,step_SN,...,-5.656179e+85,-1.000000e+99,-6.020549e+49,1.623487e-07,0.014351,3.993206,1.284869,1.284869,1.284869,1.284869
999944,detached,NaN,5.691558e+09,3802.988938,3998.959992,0.794054,NaN,NaN,NaN,step_SN,...,0.000000e+00,-1.000000e+99,-2.418984e+50,1.107203e-05,0.561762,11.825139,1.384098,1.384588,1.384098,1.384098

In [10]:
solBHdf_history['S2_mass'].describe()

count    41247.000000
mean        21.608577
std          9.799822
min          0.021281
25%         13.996429
50%         20.043755
75%         27.569154
max         51.783353
Name: S2_mass, dtype: float64

In [ ]:
binary_indices = solBHdf_history.index.unique().tolist()  
full_binary_histories = pop.history[binary_indices]

In [13]:
full_binary_histories

,state,event,time,separation,orbital_period,eccentricity,rl_relative_overflow_1,rl_relative_overflow_2,lg_mtransfer_rate,step_names,...,S2_conv_env_turnover_time_l_b,S2_conv_env_turnover_time_l_t,S2_envelope_binding_energy,S2_mass_conv_reg_fortides,S2_thickness_conv_reg_fortides,S2_radius_conv_reg_fortides,S2_lambda_CE_1cent,S2_lambda_CE_10cent,S2_lambda_CE_30cent,S2_lambda_CE_pure_He_star_10cent
binary_index,,,,,,,,,,,,,,,,,,,,,
34,detached,ZAMS,1.354058e+10,314.927115,86.368549,0.000000,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,detached,CC1,1.354658e+10,407.331945,165.622127,0.000000,-0.997212,-0.942269,-99.0,step_HMS_HMS,...,0.000000e+00,-2.162275e+97,-1.468406e+50,0.000005,0.347870,9.396873,1.118066,1.118066,1.118066,1.118093
34,detached,NaN,1.354658e+10,1131.739444,773.934254,0.706087,NaN,NaN,NaN,step_SN,...,0.000000e+00,-2.162275e+97,-1.468406e+50,0.000005,0.347870,9.396873,1.118066,1.118066,1.118066,1.118093
34,RLO2,oRLO2,1.354972e+10,348.887122,134.355473,0.000000,-1.000000,-0.050000,NaN,step_detached,...,-1.297658e+91,-1.000000e+99,-8.312169e+49,0.852111,1.135281,3.874370,0.075216,0.090221,0.120962,0.058415
34,detached,CC2,1.355034e+10,412.728901,219.512282,0.000000,-1.000000,-0.996482,-99.0,step_CO_HMS_RLO,...,0.000000e+00,0.000000e+00,0.000000e+00,0.264097,0.019860,0.070168,0.030700,0.038918,0.065229,0.545874
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999944,RLO2,oRLO2,5.693513e+09,867.136679,458.171060,0.000000,-1.000000,-0.050000,NaN,step_detached,...,1.053173e-01,2.599454e+06,-1.495715e+50,0.530810,6.520921,25.961960,0.026064,0.031910,0.046850,0.024513
999944,detached,CC2,5.693954e+09,872.001660,583.267413,0.000000,-1.000000,-0.998819,-99.0,step_CO_HMS_RLO,...,0.000000e+00,-5.890147e+97,0.000000e+00,0.417219,0.014913,0.189638,0.021311,0.026597,0.041670,0.616804
999944,detached,NaN,5.693954e+09,716.872613,439.858296,0.219448,NaN,NaN,NaN,step_SN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999944,detached,maxtime,1.380000e+10,716.872404,439.858105,0.219448,-1.000000,-1.000000,NaN,step_dco,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999944,detached,END,1.380000e+10,716.872404,439.858105,0.219448,-1.000000,-1.000000,NaN,step_end,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pop.export_selection(solBHdf_history.index.to_list(), str(DataPath / 'bhSolSubpop.h5'), append=False, overwrite = False)

FileExistsError: /gpfs/projects/b1095/bku2126/stellarBHs/Data/bhSolSubpop.h5 already exists! Set overwrite or append to True to continue!

In [13]:
solBHdf_history

,state,event,time,separation,orbital_period,eccentricity,rl_relative_overflow_1,rl_relative_overflow_2,lg_mtransfer_rate,step_names,...,S2_conv_env_turnover_time_l_b,S2_conv_env_turnover_time_l_t,S2_envelope_binding_energy,S2_mass_conv_reg_fortides,S2_thickness_conv_reg_fortides,S2_radius_conv_reg_fortides,S2_lambda_CE_1cent,S2_lambda_CE_10cent,S2_lambda_CE_30cent,S2_lambda_CE_pure_He_star_10cent
binary_index,,,,,,,,,,,,,,,,,,,,,
34,detached,NaN,1.354658e+10,1131.739444,773.934254,0.706087,NaN,NaN,NaN,step_SN,...,0.000000e+00,-2.162275e+97,-1.468406e+50,4.762350e-06,0.347870,9.396873,1.118066,1.118066,1.118066,1.118093
40,detached,NaN,9.365578e+08,74.435662,13.464326,0.221966,NaN,NaN,NaN,step_SN,...,0.000000e+00,-5.929734e+98,-1.739592e+50,1.689453e+00,0.363708,2.030009,0.899983,0.719876,0.720830,1.184937
66,detached,NaN,7.320985e+08,198.318680,42.991418,0.046120,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-2.504154e+50,1.177150e-01,3.231943,19.644430,0.592405,0.232861,0.265062,0.592405
83,detached,NaN,4.982609e+08,50.407465,10.559919,0.639463,NaN,NaN,NaN,step_SN,...,-1.834669e+87,-1.000000e+99,-7.499487e+49,3.481643e-07,0.031008,4.687843,1.295121,1.295121,1.295121,1.295121
86,detached,NaN,1.001154e+10,176.105411,38.437130,0.318287,NaN,NaN,NaN,step_SN,...,0.000000e+00,-6.928767e+98,-2.679997e+50,2.561434e-05,0.951441,13.888433,1.342558,1.343758,1.036638,1.342558
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999858,detached,NaN,8.317989e+09,63.091987,10.937788,0.190515,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-1.291544e+50,3.205125e-06,0.213334,6.881290,1.173028,1.173028,1.173028,1.173162
999861,detached,NaN,1.068474e+10,883.381417,573.468964,0.432775,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-7.867066e+49,5.785900e-07,0.038229,4.391969,1.311851,1.311851,1.311851,1.314639
999931,detached,NaN,9.064239e+09,7530.879233,18964.253312,0.969098,NaN,NaN,NaN,step_SN,...,0.000000e+00,0.000000e+00,-8.444020e+49,1.939937e-01,0.108014,4.283201,1.090792,1.090792,1.090792,1.091467
999940,detached,NaN,9.362281e+09,9.474144,0.941797,0.688918,NaN,NaN,NaN,step_SN,...,-5.656179e+85,-1.000000e+99,-6.020549e+49,1.623487e-07,0.014351,3.993206,1.284869,1.284869,1.284869,1.284869
999944,detached,NaN,5.691558e+09,3802.988938,3998.959992,0.794054,NaN,NaN,NaN,step_SN,...,0.000000e+00,-1.000000e+99,-2.418984e+50,1.107203e-05,0.561762,11.825139,1.384098,1.384588,1.384098,1.384098