In [1]:
import pandas as pd
from pathlib import Path

# from posydon.popsyn.binarypopulation import BinaryPopulation
# from posydon.binary_evol.binarystar import BinaryStar
# from posydon.binary_evol.singlestar import SingleStar
from posydon.popsyn.synthetic_population import Population
# from posydon.popsyn.synthetic_population import PopulationRunner
# import astropy.units as u

# import os
# import shutil
# from posydon.config import PATH_TO_POSYDON

# from POSYDONHRDiagramModule import HR_Diagram
# import matplotlib.pyplot as plt
# import random as rand 

from collections import Counter

DataPath = Path().resolve().parent.parent.parent / 'Data'

In [2]:
cols = ['time', 'step_names', 'state', 'event', 'S1_state', 'S2_state', 'S1_mass', 'S2_mass', 'orbital_period']
finCols = [
    'orbital_period_f',
    'eccentricity_f',
    'state_f',

    'S1_state_f',
    'S2_state_f',
    
    'S2_mass_f',
    'S2_log_R_f',
    'S2_log_L_f',


    'S1_mass_f',
    'S1_log_R_f',
    'S1_log_L_f'

 ]

initCols = [
    'orbital_period_i',
    'eccentricity_i',
    'state_i',

    'S2_state_i',
    'S2_mass_i',
    'S2_log_R_i',

    'S1_state_i',
    'S1_mass_i',
    'S1_log_R_i'
 ]

In [3]:
pop = Population(str(DataPath / 'bhSolSubpop.h5'))

Missing ini parameter: posydon_version

In [4]:
len(pop)

41191

In [5]:
# pop.calculate_formation_channels()

In [6]:
Counter(pop.formation_channels['channel'])

Counter({'ZAMS_oRLO1_CC1_oRLO2_CC2_END': 14627,
         'ZAMS_oRLO1_CC1_oRLO2_CC2_maxtime_END': 8016,
         'ZAMS_CC1_oRLO2_CC2_maxtime_END': 4146,
         'ZAMS_CC1_oRLO2_CC2_END': 4133,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_oMerging2_END': 3180,
         'ZAMS_oRLO1_CC1_END': 1327,
         'ZAMS_CC1_CC2_END': 1180,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_CC2_END': 1092,
         'ZAMS_CC1_CC2_maxtime_END': 815,
         'ZAMS_CC1_oRLO2_oCE2_oMerging2_END': 413,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_CC2_maxtime_END': 338,
         'ZAMS_oCE1_CC1_oRLO2_CC2_maxtime_END': 279,
         'ZAMS_oRLO1-contact_CC1_oRLO2_oCE2_oMerging2_END': 268,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_END': 243,
         'ZAMS_oRLO1_CC1_CC2_END': 191,
         'ZAMS_oRLO1-contact_CC1_END': 158,
         'ZAMS_oRLO1_CC1_CC2_maxtime_END': 122,
         'ZAMS_oCE1_CC1_END': 99,
         'ZAMS_CC1_END': 95,
         'ZAMS_oCE1_CC1_oRLO2_oCE2_oMerging2_END': 90,
         'ZAMS_oCE1_CC1_oRLO2_CC2_END': 59,
         'ZAMS_oRLO1_CC1_maxtime_END': 51,
         'ZAMS_oRLO1-reverse_CC1_END': 44,
         'ZAMS_oRLO1-contact_CC1_oRLO2_CC2_maxtime_END': 37,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_CC2_maxtime_END': 33,
         'ZAMS_oRLO1-contact_CC1_oRLO2_CC2_END': 31,
         'ZAMS_CC1_oRLO2_oCE2_CC2_maxtime_END': 31,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_CC2_END': 20,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_oCE2_oMerging2_END': 20,
         'ZAMS_CC1_maxtime_END': 15,
         'ZAMS_oCE1_CC1_oRLO2_CC2_FAILED': 14,
         'ZAMS_oRLO1-contact_CC1_CC2_maxtime_END': 12,
         'ZAMS_oCE1_CC1_maxtime_END': 12,
         'ZAMS_oRLO1-reverse_CC1_CC2_maxtime_END': 10,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_oCE2_oMerging2_END': 9,
         'ZAMS_CC1_oRLO2_oCE2_CC2_END': 7,
         'ZAMS_oCE1_CC1_CC2_maxtime_END': 5,
         'ZAMS_oCE1_CC1_oRLO2_maxtime_END': 5,
         'ZAMS_oRLO1_CC1_oRLO2_maxtime_END': 4,
         'ZAMS_oRLO1_CC1_FAILED_FAILED': 4,
         'ZAMS_CC1_FAILED_FAILED': 4,
         'ZAMS_oRLO1_CC1_oRLO2_oCE2_CC2_FAILED_FAILED': 3,
         'ZAMS_oRLO1-reverse_CC1_CC2_END': 2,
         'ZAMS_oRLO1_CC1_oRLO2_CC2_FAILED': 1,
         'ZAMS_CC1_oRLO2_END': 1,
         'ZAMS_oRLO1-reverse_CC1_oRLO2_oCE2_END': 1})

In [7]:
solBH_oneline_df = pop.oneline.select()
solBH_history_df = pop.history.select()

In [8]:
solBH_oneline_df

,state_i,event_i,time_i,separation_i,orbital_period_i,eccentricity_i,rl_relative_overflow_1_i,rl_relative_overflow_2_i,lg_mtransfer_rate_i,step_names_i,...,interp_class_CO_HMS_RLO,interp_class_CO_HeMS,interp_class_CO_HeMS_RLO,mt_history_HMS_HMS,mt_history_CO_HMS_RLO,mt_history_CO_HeMS,mt_history_CO_HeMS_RLO,FAILED,WARNING,metallicity
binary_index,,,,,,,,,,,,,,,,,,,,,
0,detached,ZAMS,1.354058e+10,314.927115,86.368549,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Last stable RLOF during postMS,Last stable RLOF during postMS,NaN,NaN,0,0,1.0
1,detached,ZAMS,9.269310e+08,42.893063,4.949364,0.0,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,Stable contact phase,NaN,NaN,NaN,0,1,1.0
2,detached,ZAMS,7.282359e+08,83.936347,7.613953,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,no RLOF,Last stable RLOF during postMS,NaN,NaN,0,0,1.0
3,detached,ZAMS,4.896616e+08,346.312644,129.999715,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Unstable RLOF during postMS,Last stable RLOF during stripped He star,NaN,NaN,0,1,1.0
4,detached,ZAMS,1.000807e+10,77.296905,6.337424,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,no RLOF,Last stable RLOF during postMS,NaN,NaN,0,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41242,detached,ZAMS,8.312676e+09,79.470260,10.689626,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Last stable RLOF during postMS,Last stable RLOF during postMS,NaN,NaN,0,0,1.0
41243,detached,ZAMS,1.067994e+10,792.218696,331.835337,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,no RLOF,Last stable RLOF during postMS,NaN,NaN,0,0,1.0
41244,detached,ZAMS,9.054567e+09,285.509574,96.941221,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,Last stable RLOF during postMS,Last stable RLOF during postMS,NaN,NaN,0,0,1.0
41245,detached,ZAMS,9.352825e+09,372.819841,154.288032,0.0,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,Unstable RLOF during postMS,NaN,NaN,NaN,0,1,1.0
41246,detached,ZAMS,5.687928e+09,286.403130,49.544310,0.0,NaN,NaN,NaN,initial_cond,...,stable_MT,NaN,NaN,no RLOF,Last stable RLOF during postMS,NaN,NaN,0,0,1.0

In [9]:
sol_bhInitMask = (
    ((solBH_history_df['S1_state'] == 'BH') & (solBH_history_df['S2_state'] == 'H-rich_Core_H_burning')) |
    ((solBH_history_df['S2_state'] == 'BH') & (solBH_history_df['S1_state'] == 'H-rich_Core_H_burning'))
) & (solBH_history_df['event'] != 'END')

sol_bhMaskNext = sol_bhInitMask.groupby(level=0).shift(1, fill_value=False)

sol_bhMaskPrev = sol_bhInitMask.groupby(level=0).shift(-1, fill_value=False)


sol_bhMask = sol_bhInitMask | sol_bhMaskNext

specStatedf = solBH_history_df[sol_bhMask] ### makes a df with the row with the sol-bh and the row after. used for finding the lifespan of the systems 

sol_bhMaskFirst = pd.Series(False, index = sol_bhMask.index)
sol_bhMaskFirst = ~sol_bhMaskFirst.index.duplicated(keep='first')

firstAndsol_bh = sol_bhInitMask | sol_bhMaskFirst
### makes a mask with the init cond and the row with the bh-sol, not super useful when compared to just using bh-ms row df + oneline 

def isMW(group): ### this is wayyyyy too narrow of a process... it does work though!
    return (group['time'].iloc[0] < 10e9) & (group['time'].iloc[1] > 10e9)
TenGyr = solBH_history_df[sol_bhMask].groupby(level=0).apply(isMW)

def findStatDur(group):
        return (group['time'].iloc[1] - group['time'].iloc[0])

In [10]:
solBH_history_df[cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
0,1.354058e+10,initial_cond,detached,ZAMS,H-rich_Core_H_burning,H-rich_Core_H_burning,35.594066,20.634703,86.368549
0,1.354658e+10,step_HMS_HMS,detached,CC1,stripped_He_Core_C_depleted,H-rich_Core_H_burning,12.319972,20.766340,165.622127
0,1.354658e+10,step_SN,detached,NaN,BH,H-rich_Core_H_burning,11.742339,20.766340,773.934254
0,1.354972e+10,step_detached,RLO2,oRLO2,BH,H-rich_Shell_H_burning,11.742339,19.859488,134.355473
0,1.355034e+10,step_CO_HMS_RLO,detached,CC2,BH,stripped_He_Core_C_depleted,11.747448,7.846260,219.512282
...,...,...,...,...,...,...,...,...,...
41246,5.693513e+09,step_detached,RLO2,oRLO2,BH,H-rich_Shell_H_burning,13.275789,28.447204,458.171060
41246,5.693954e+09,step_CO_HMS_RLO,detached,CC2,BH,stripped_He_Core_C_depleted,13.278808,12.894353,583.267413
41246,5.693954e+09,step_SN,detached,NaN,BH,BH,13.278808,12.299305,439.858296
41246,1.380000e+10,step_dco,detached,maxtime,BH,BH,13.278808,12.299305,439.858105
41246,1.380000e+10,step_end,detached,END,BH,BH,13.278808,12.299305,439.858105

In [11]:
solBH_history_df[sol_bhMaskPrev][cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
0,1.354658e+10,step_HMS_HMS,detached,CC1,stripped_He_Core_C_depleted,H-rich_Core_H_burning,12.319972,20.766340,165.622127
1,9.365578e+08,step_HMS_HMS,detached,CC1,stripped_He_Core_C_depleted,H-rich_Core_H_burning,7.021549,27.696843,15.563316
1,9.365578e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.862360,27.696843,13.464326
2,7.320985e+08,step_HMS_HMS,detached,CC1,stripped_He_Core_C_depleted,H-rich_Core_H_burning,14.545746,42.583776,40.571727
3,4.982609e+08,step_detached,detached,CC1,stripped_He_Core_He_depleted,H-rich_Core_H_burning,8.301513,11.088933,2.042400
...,...,...,...,...,...,...,...,...,...
41243,1.068474e+10,step_HMS_HMS,detached,CC1,stripped_He_Core_C_depleted,H-rich_Core_H_burning,17.612600,11.066489,974.356911
41244,9.064239e+09,step_HMS_HMS,detached,CC1,stripped_He_Core_C_depleted,H-rich_Core_H_burning,7.620827,12.382211,133.934585
41245,9.362281e+09,step_detached,detached,CC1,stripped_He_Core_He_depleted,H-rich_Core_H_burning,7.396282,9.131854,1.514407
41245,9.362281e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.746892,9.131854,0.941797
41246,5.691558e+09,step_HMS_HMS,detached,CC1,stripped_He_Core_C_depleted,H-rich_Core_H_burning,13.775318,32.924976,372.957975

In [12]:
solBH_history_df[sol_bhInitMask][cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
0,1.354658e+10,step_SN,detached,NaN,BH,H-rich_Core_H_burning,11.742339,20.766340,773.934254
1,9.365578e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.862360,27.696843,13.464326
1,9.365578e+08,step_detached,initial_RLOF,NaN,BH,H-rich_Core_H_burning,2.862360,27.479589,13.464326
2,7.320985e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,14.104784,42.583776,42.991418
3,4.982609e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.339844,11.088933,10.559919
...,...,...,...,...,...,...,...,...,...
41243,1.068474e+10,step_SN,detached,NaN,BH,H-rich_Core_H_burning,17.090943,11.066489,573.468964
41244,9.064239e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.570469,12.382211,18964.253312
41245,9.362281e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.746892,9.131854,0.941797
41245,9.362281e+09,step_detached,initial_RLOF,NaN,BH,H-rich_Core_H_burning,3.746892,9.135707,0.941797
41246,5.691558e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,13.275789,32.924976,3998.959992

In [13]:
solBH_history_df[sol_bhMaskNext][cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
0,1.354972e+10,step_detached,RLO2,oRLO2,BH,H-rich_Shell_H_burning,11.742339,19.859488,134.355473
1,9.365578e+08,step_detached,initial_RLOF,NaN,BH,H-rich_Core_H_burning,2.862360,27.479589,13.464326
1,9.365578e+08,step_end,initial_RLOF,END,BH,H-rich_Core_H_burning,2.862360,27.479589,13.464326
2,7.322479e+08,step_detached,RLO2,oRLO2,BH,H-rich_Shell_H_burning,14.104784,40.612676,43.774270
3,5.087332e+08,step_detached,RLO2,oRLO2,BH,H-rich_Core_H_burning,4.339844,10.922052,2.375617
...,...,...,...,...,...,...,...,...,...
41243,1.070262e+10,step_detached,RLO2,oRLO2,BH,H-rich_Shell_H_burning,17.090943,10.705854,251.615171
41244,9.073686e+09,step_detached,RLO2,oRLO2,BH,H-rich_Shell_H_burning,3.570469,11.957024,108.973657
41245,9.362281e+09,step_detached,initial_RLOF,NaN,BH,H-rich_Core_H_burning,3.746892,9.135707,0.941797
41245,9.362281e+09,step_end,initial_RLOF,END,BH,H-rich_Core_H_burning,3.746892,9.135707,0.941797
41246,5.693513e+09,step_detached,RLO2,oRLO2,BH,H-rich_Shell_H_burning,13.275789,28.447204,458.171060

In [14]:
solBH_history_df

,state,event,time,separation,orbital_period,eccentricity,rl_relative_overflow_1,rl_relative_overflow_2,lg_mtransfer_rate,step_names,...,S2_conv_env_turnover_time_l_b,S2_conv_env_turnover_time_l_t,S2_envelope_binding_energy,S2_mass_conv_reg_fortides,S2_thickness_conv_reg_fortides,S2_radius_conv_reg_fortides,S2_lambda_CE_1cent,S2_lambda_CE_10cent,S2_lambda_CE_30cent,S2_lambda_CE_pure_He_star_10cent
binary_index,,,,,,,,,,,,,,,,,,,,,
0,detached,ZAMS,1.354058e+10,314.927115,86.368549,0.000000,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,detached,CC1,1.354658e+10,407.331945,165.622127,0.000000,-0.997212,-0.942269,-99.0,step_HMS_HMS,...,0.000000e+00,-2.162275e+97,-1.468406e+50,0.000005,0.347870,9.396873,1.118066,1.118066,1.118066,1.118093
0,detached,NaN,1.354658e+10,1131.739444,773.934254,0.706087,NaN,NaN,NaN,step_SN,...,0.000000e+00,-2.162275e+97,-1.468406e+50,0.000005,0.347870,9.396873,1.118066,1.118066,1.118066,1.118093
0,RLO2,oRLO2,1.354972e+10,348.887122,134.355473,0.000000,-1.000000,-0.050000,NaN,step_detached,...,-1.297658e+91,-1.000000e+99,-8.312169e+49,0.852111,1.135281,3.874370,0.075216,0.090221,0.120962,0.058415
0,detached,CC2,1.355034e+10,412.728901,219.512282,0.000000,-1.000000,-0.996482,-99.0,step_CO_HMS_RLO,...,0.000000e+00,0.000000e+00,0.000000e+00,0.264097,0.019860,0.070168,0.030700,0.038918,0.065229,0.545874
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41246,RLO2,oRLO2,5.693513e+09,867.136679,458.171060,0.000000,-1.000000,-0.050000,NaN,step_detached,...,1.053173e-01,2.599454e+06,-1.495715e+50,0.530810,6.520921,25.961960,0.026064,0.031910,0.046850,0.024513
41246,detached,CC2,5.693954e+09,872.001660,583.267413,0.000000,-1.000000,-0.998819,-99.0,step_CO_HMS_RLO,...,0.000000e+00,-5.890147e+97,0.000000e+00,0.417219,0.014913,0.189638,0.021311,0.026597,0.041670,0.616804
41246,detached,NaN,5.693954e+09,716.872613,439.858296,0.219448,NaN,NaN,NaN,step_SN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41246,detached,maxtime,1.380000e+10,716.872404,439.858105,0.219448,-1.000000,-1.000000,NaN,step_dco,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41246,detached,END,1.380000e+10,716.872404,439.858105,0.219448,-1.000000,-1.000000,NaN,step_end,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
solBH_history_df

,state,event,time,separation,orbital_period,eccentricity,rl_relative_overflow_1,rl_relative_overflow_2,lg_mtransfer_rate,step_names,...,S2_conv_env_turnover_time_l_b,S2_conv_env_turnover_time_l_t,S2_envelope_binding_energy,S2_mass_conv_reg_fortides,S2_thickness_conv_reg_fortides,S2_radius_conv_reg_fortides,S2_lambda_CE_1cent,S2_lambda_CE_10cent,S2_lambda_CE_30cent,S2_lambda_CE_pure_He_star_10cent
binary_index,,,,,,,,,,,,,,,,,,,,,
0,detached,ZAMS,1.354058e+10,314.927115,86.368549,0.000000,NaN,NaN,NaN,initial_cond,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,detached,CC1,1.354658e+10,407.331945,165.622127,0.000000,-0.997212,-0.942269,-99.0,step_HMS_HMS,...,0.000000e+00,-2.162275e+97,-1.468406e+50,0.000005,0.347870,9.396873,1.118066,1.118066,1.118066,1.118093
0,detached,NaN,1.354658e+10,1131.739444,773.934254,0.706087,NaN,NaN,NaN,step_SN,...,0.000000e+00,-2.162275e+97,-1.468406e+50,0.000005,0.347870,9.396873,1.118066,1.118066,1.118066,1.118093
0,RLO2,oRLO2,1.354972e+10,348.887122,134.355473,0.000000,-1.000000,-0.050000,NaN,step_detached,...,-1.297658e+91,-1.000000e+99,-8.312169e+49,0.852111,1.135281,3.874370,0.075216,0.090221,0.120962,0.058415
0,detached,CC2,1.355034e+10,412.728901,219.512282,0.000000,-1.000000,-0.996482,-99.0,step_CO_HMS_RLO,...,0.000000e+00,0.000000e+00,0.000000e+00,0.264097,0.019860,0.070168,0.030700,0.038918,0.065229,0.545874
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41246,RLO2,oRLO2,5.693513e+09,867.136679,458.171060,0.000000,-1.000000,-0.050000,NaN,step_detached,...,1.053173e-01,2.599454e+06,-1.495715e+50,0.530810,6.520921,25.961960,0.026064,0.031910,0.046850,0.024513
41246,detached,CC2,5.693954e+09,872.001660,583.267413,0.000000,-1.000000,-0.998819,-99.0,step_CO_HMS_RLO,...,0.000000e+00,-5.890147e+97,0.000000e+00,0.417219,0.014913,0.189638,0.021311,0.026597,0.041670,0.616804
41246,detached,NaN,5.693954e+09,716.872613,439.858296,0.219448,NaN,NaN,NaN,step_SN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41246,detached,maxtime,1.380000e+10,716.872404,439.858105,0.219448,-1.000000,-1.000000,NaN,step_dco,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41246,detached,END,1.380000e+10,716.872404,439.858105,0.219448,-1.000000,-1.000000,NaN,step_end,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df = solBH_history_df

BH_Sol_Mask = (
        (df['S1_state'] == 'BH') & (df['S2_state'] == 'H-rich_Core_H_burning')
        &  (df['state'] == 'detached')
        &  (df['S2_mass'] < float(3.5)) & (df['orbital_period'] < float(300))
        &  (df['S2_mass'] > .4)
        &  (df['time'] < 10e9)
    )

PrevRowMask = BH_Sol_Mask.groupby(level=0).shift(-1, fill_value=False)
AftRowMask = BH_Sol_Mask.groupby(level=0).shift(1, fill_value=False)

filtPop_df = df[BH_Sol_Mask]
PrevRow    = df[PrevRowMask]
AftRow     = df[AftRowMask]

In [17]:
output_dir = Path().resolve().parent / 'temp'

outputName = 'temp'

In [18]:
df_csv_OutputPath = (output_dir / outputName)

In [19]:
filtPop_df.to_csv(str(df_csv_OutputPath.with_suffix('.csv')))
PrevRow.to_csv(str(((output_dir / (outputName +'prevRow'))).with_suffix('.csv')))
AftRow.to_csv(str(((output_dir / (outputName +'AftRow'))).with_suffix('.csv')))

In [20]:
sol_bh_lifespan_list = specStatedf.groupby(level=0).apply(findStatDur)
sol_bh_FormationTime_List = solBH_history_df[firstAndsol_bh].groupby(level=0).apply(findStatDur)

In [21]:
sol_bh_lifespan_list.describe()

count    4.119100e+04
mean     7.961639e+06
std      2.094689e+07
min      0.000000e+00
25%      1.145769e+06
50%      3.525567e+06
75%      9.046779e+06
max      1.373802e+09
dtype: float64

In [22]:
sol_bh_FormationTime_List.describe()

count    4.119100e+04
mean     6.106691e+06
std      3.651581e+07
min      3.200919e+06
25%      4.176094e+06
50%      5.230424e+06
75%      6.702036e+06
max      5.568467e+09
dtype: float64

In [23]:

sol_bhMaskMWdur = ((
    ((solBH_history_df['S1_state'] == 'BH') & (solBH_history_df['S2_state'] == 'H-rich_Core_H_burning'))
    )   & (solBH_history_df['event'] != 'END')
        & (solBH_history_df['time'] < 10e9)
        & (solBH_history_df['state'] == 'detached')
)

In [24]:
len(solBH_history_df[sol_bhMaskMWdur])

29759

In [25]:
solBH_history_df[sol_bhMaskMWdur][cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
1,9.365578e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.862360,27.696843,13.464326
2,7.320985e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,14.104784,42.583776,42.991418
3,4.982609e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.339844,11.088933,10.559919
5,9.257842e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,16.217696,25.023889,2185.162950
7,5.187019e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,13.837255,30.757624,1073.146224
...,...,...,...,...,...,...,...,...,...
41241,6.492712e+08,step_SN,detached,NaN,BH,H-rich_Core_H_burning,12.734073,46.109216,263.124746
41242,8.317989e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,11.144016,17.054852,10.937788
41244,9.064239e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.570469,12.382211,18964.253312
41245,9.362281e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.746892,9.131854,0.941797
41246,5.691558e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,13.275789,32.924976,3998.959992

In [26]:
lowPorbSolBH = solBH_history_df[sol_bhMaskMWdur][solBH_history_df[sol_bhMaskMWdur]['orbital_period'] < 3]

In [27]:
lowPorbSolBH[cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
65,4.388148e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.510452,7.542214,2.552592
204,4.717553e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.864177,7.439176,2.078860
261,9.005453e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.720699,7.515792,2.597624
281,8.861886e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.548404,7.243093,2.914340
336,3.671609e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.481917,6.927287,2.674174
...,...,...,...,...,...,...,...,...,...
40849,2.593308e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.521511,5.991479,1.456001
40965,4.703897e+07,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.372229,12.649951,2.995665
41103,2.936772e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.885103,7.898216,1.440654
41150,6.852416e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.973341,8.338666,1.801697
41245,9.362281e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.746892,9.131854,0.941797

In [28]:
lowPorbSolBH.to_csv(DataPath / 'threeDayPorb_solBHPairRows.csv')

In [29]:
pop.export_selection(lowPorbSolBH.index.to_list(), str(DataPath / 'bhSol_10Gyr_LowPorb_Subpop.h5'), append=False, overwrite=False)

FileExistsError: /gpfs/projects/b1095/bku2126/stellarBHs/Data/bhSol_10Gyr_LowPorb_Subpop.h5 already exists! Set overwrite or append to True to continue!

In [30]:
FiveDPorbSolBH = solBH_history_df[sol_bhMaskMWdur][solBH_history_df[sol_bhMaskMWdur]['orbital_period'] < 5]

In [31]:
FiveDPorbSolBH[cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
65,4.388148e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.510452,7.542214,2.552592
100,6.723392e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,6.746752,23.365053,4.711448
121,6.348326e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.705900,29.010861,3.227938
163,4.091260e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.549543,23.219983,3.035637
189,2.120485e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.739360,6.555099,3.598046
...,...,...,...,...,...,...,...,...,...
41093,9.813266e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.077906,6.586934,4.465087
41103,2.936772e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.885103,7.898216,1.440654
41150,6.852416e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,2.973341,8.338666,1.801697
41184,9.026899e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.347515,20.683932,4.818280
41245,9.362281e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.746892,9.131854,0.941797

In [32]:
FiveDPorbSolBH[FiveDPorbSolBH['S2_mass'] < 2.5][cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
2802,3.691715e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.747350,1.911536,1.849214
8266,7.081756e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,2.785568,0.091402,3.097021
20583,5.462662e+09,step_CO_HMS_RLO,detached,CC2,BH,H-rich_Core_H_burning,2.543167,0.084394,2.159860
23416,9.633998e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.352769,2.491193,2.778295
36945,8.068772e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,4.664751,2.208363,0.459428

In [33]:
pop.export_selection(FiveDPorbSolBH.index.to_list(), str(DataPath / 'bhSol_10Gyr_FiveDay_Subpop.h5'), append=False, overwrite=True)

Missing ini parameter: posydon_version

In [34]:
filtPop = Population(str(DataPath / 'bhSol_10Gyr_LowPorb_Subpop.h5'))

Missing ini parameter: posydon_version

In [35]:
len(filtPop)

454

In [36]:
filtPop.history.select()[cols]

,time,step_names,state,event,S1_state,S2_state,S1_mass,S2_mass,orbital_period
binary_index,,,,,,,,,
0,4.379912e+09,initial_cond,detached,ZAMS,H-rich_Core_H_burning,H-rich_Core_H_burning,25.281532,6.978345,14.862365
0,4.388148e+09,step_HMS_HMS,detached,CC1,stripped_He_Core_C_depleted,H-rich_Core_H_burning,7.509545,7.542214,2.124767
0,4.388148e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.510452,7.542214,2.552592
0,4.421309e+09,step_detached,RLO2,oRLO2,BH,H-rich_Core_H_burning,3.510452,7.610958,2.270194
0,4.448127e+09,step_CO_HMS_RLO,detached,CC2,BH,stripped_He_Core_He_depleted,4.144812,0.893005,20.743069
...,...,...,...,...,...,...,...,...,...
453,9.362273e+09,step_CE,detached,NaN,stripped_He_non_burning,H-rich_Core_H_burning,7.457188,9.061668,1.493836
453,9.362281e+09,step_detached,detached,CC1,stripped_He_Core_He_depleted,H-rich_Core_H_burning,7.396282,9.131854,1.514407
453,9.362281e+09,step_SN,detached,NaN,BH,H-rich_Core_H_burning,3.746892,9.131854,0.941797
453,9.362281e+09,step_detached,initial_RLOF,NaN,BH,H-rich_Core_H_burning,3.746892,9.135707,0.941797
453,9.362281e+09,step_end,initial_RLOF,END,BH,H-rich_Core_H_burning,3.746892,9.135707,0.941797